pipeline:
    name: SimplePipeline
    identifier: SimplePipeline
    projectIdentifier: GitSyncDemo
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Turn Flag On
              identifier: Turn_Flag_On
              description: ""
              type: FeatureFlag
              spec:
                  execution:
                      steps:
                          - step:
                                type: FlagConfiguration
                                name: Turn Flag On
                                identifier: Turn_Flag_On
                                spec:
                                    feature: SimpleString
                                    environment: Prod1
                                    instructions:
                                        - identifier: SetFeatureFlagStateIdentifier
                                          type: SetFeatureFlagState
                                          spec:
                                              state: "on"
                                timeout: 10m
